import 'package:cathcrop_beta/home.dart';
import 'package:flutter/material.dart';
import 'home.dart';

class market extends StatelessWidget {
  const market({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 4,
      child: Scaffold(
          body: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return [
            SliverAppBar(
              backgroundColor: Colors.white,
              shadowColor: Colors.black,
              toolbarHeight: 150,
              forceElevated: true,
              title: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    child: ListTile(
                      leading: Image.asset("assets/images/btc.png"),
                      title: Row(
                        children: [
                          Text(
                            "BTC/USDT",
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 15,
                              fontFamily: "Abhaya_Libre",
                            ),
                          ),
                          SizedBox(
                            width: 3,
                          ),
                          Text(
                            "+4.7%",
                            style: TextStyle(
                              color: Colors.green,
                              fontSize: 15,
                              fontFamily: "Poppins",
                            ),
                          ),
                        ],
                      ),
                      subtitle: Text(
                        "SON 24 SAAT",
                        style: TextStyle(
                          color: Colors.grey,
                          fontSize: 10,
                          fontFamily: "Poppins",
                        ),
                      ),
                      trailing: Icon(
                        Icons.search,
                        size: 25,
                      ),
                    ),
                  ),
                  SizedBox(
                    height: 20,
                  ),
                  Container(
                    margin: EdgeInsets.only(left: 17),
                    child: Text(
                      "Coinler",
                      style: TextStyle(
                        color: Colors.black,
                      ),
                    ),
                  ),
                ],
              ),
              pinned: true,
              floating: false,
              bottom: TabBar(
                labelColor: Colors.black,
                labelStyle: TextStyle(
                  fontFamily: "Poppins",
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                ),
                indicatorColor: Colors.black,
                unselectedLabelColor: Colors.grey,
                indicatorSize: TabBarIndicatorSize.tab,
                isScrollable: true,
                tabs: [
                  Tab(
                    child: Text(
                      'Tümü',
                    ),
                  ),
                  Tab(
                    child: Text(
                      'Yükselenler',
                    ),
                  ),
                  Tab(
                    child: Text(
                      'Düşenler',
                    ),
                  ),
                  Tab(
                    child: Text(
                      'Popüler',
                    ),
                  ),
                ],
              ),
            ),
          ];
        },
        body: TabBarView(
          children: [
            SingleChildScrollView(
              physics: BouncingScrollPhysics(),
              child: Padding(
                padding: const EdgeInsets.all(30.0),
                child: Column(
                  children: [
                    coin_get(
                      "assets/images/bnb.png",
                      "assets/images/bnb_graph.png",
                      "Binance",
                      "BNB",
                      "    \$428.2",
                      "+3.45%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/eth.png",
                      "assets/images/down1.png",
                      "Ethereum",
                      "ETH",
                      "\$3,490.20",
                      "-1.6%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/ada.png",
                      "assets/images/down1.png",
                      "Cardano",
                      "ADA",
                      "      \$1.149",
                      "-5.12%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/doge.png",
                      "assets/images/doge_graph.png",
                      "DOGE",
                      "DOGE",
                      "      \$0.1387",
                      "+16.23%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/xrp.png",
                      "assets/images/xrp_graph.png",
                      "XRP",
                      "XRP",
                      "      \$0.089",
                      "+25.53%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/usdt.png",
                      "assets/images/usdt_graph.png",
                      "Tether",
                      "USDT",
                      "      \₺14.776",
                      "+0.11%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/ltc.png",
                      "assets/images/doge_graph.png",
                      "Uniswap",
                      "UNI",
                      "      \$11.21",
                      "+7.21%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/aave.png",
                      "assets/images/down3.png",
                      "Aave",
                      "AAVE",
                      "      \$242.13",
                      "-7.59%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/tron.png",
                      "assets/images/bnb_graph.png",
                      "Tron",
                      "TRX",
                      "      \$0.07608",
                      "+4.14%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/lite.png",
                      "assets/images/down5.png",
                      "Litecoin",
                      "LTC",
                      "      \$126.69",
                      "-3.28%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/iota.png",
                      "assets/images/down1.png",
                      "IOTA",
                      "MIOTA",
                      "    \$0.8922",
                      "-0.87%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/ecash.png",
                      "assets/images/down5.png",
                      "eCash",
                      "XEC",
                      "\$0.0001162",
                      "-13.41%%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/enj.png",
                      "assets/images/down2.png",
                      "Enjin Coin",
                      "ENJ",
                      "    \$1.86",
                      "-0.82%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/fil.png",
                      "assets/images/btc_graph.png",
                      "Filecoin",
                      "FIL",
                      "      \$25.61",
                      "+8.34%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/link.png",
                      "assets/images/down1.png",
                      "Chainlink",
                      "LINK",
                      "      \$17.41",
                      "-4.11%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/avax.png",
                      "assets/images/ada_graph.png",
                      "Avalanche",
                      "AVAX",
                      "      \$100.08",
                      "+6.91%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/ape.png",
                      "assets/images/down3.png",
                      "ApeCoin",
                      "APE",
                      "      \$13.01",
                      "-3.17%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/cosmos.png",
                      "assets/images/down1.png",
                      "Cosmos",
                      "ATOM",
                      "      \$30.02",
                      "-5.04%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/algo.png",
                      "assets/images/btc_graph.png",
                      "Algorand",
                      "ALGO",
                      "      \$0.9606",
                      "+3.28%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/vinu.png",
                      "assets/images/usdt_graph.png",
                      "Vita Inu",
                      "VINU",
                      "0,00000421",
                      "+95.21%",
                      0xFF006400,
                    ),
                  ],
                ),
              ),
            ),
            SingleChildScrollView(
              physics: BouncingScrollPhysics(),
              child: Padding(
                padding: const EdgeInsets.all(30.0),
                child: Column(
                  children: [
                    coin_get(
                      "assets/images/vinu.png",
                      "assets/images/usdt_graph.png",
                      "Vita Inu",
                      "VINU",
                      "0,00000421",
                      "+95.21%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/xrp.png",
                      "assets/images/xrp_graph.png",
                      "XRP",
                      "XRP",
                      "      \$0.089",
                      "+25.53%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/doge.png",
                      "assets/images/doge_graph.png",
                      "DOGE",
                      "DOGE",
                      "      \$0.1387",
                      "+16.23%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/fil.png",
                      "assets/images/btc_graph.png",
                      "Filecoin",
                      "FIL",
                      "      \$25.61",
                      "+8.34%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/ltc.png",
                      "assets/images/doge_graph.png",
                      "Uniswap",
                      "UNI",
                      "      \$11.21",
                      "+7.21%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/avax.png",
                      "assets/images/ada_graph.png",
                      "Avalanche",
                      "AVAX",
                      "      \$100.08",
                      "+6.91%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/ada.png",
                      "assets/images/ada_graph.png",
                      "Cardano",
                      "ADA",
                      "      \$1.149",
                      "+5.12%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/tron.png",
                      "assets/images/bnb_graph.png",
                      "Tron",
                      "TRX",
                      "      \$0.07608",
                      "+4.14%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/bnb.png",
                      "assets/images/bnb_graph.png",
                      "Binance",
                      "BNB",
                      "    \$428.2",
                      "+3.45%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/algo.png",
                      "assets/images/btc_graph.png",
                      "Algorand",
                      "ALGO",
                      "      \$0.9606",
                      "+3.28%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/usdt.png",
                      "assets/images/usdt_graph.png",
                      "Tether",
                      "USDT",
                      "      \₺14.776",
                      "+0.11%",
                      0xFF006400,
                    ),

                  ],
                ),
              ),
            ),
            SingleChildScrollView(
              physics: BouncingScrollPhysics(),
              child: Padding(
                padding: const EdgeInsets.all(30.0),
                child: Column(
                  children: [
                    coin_get(
                      "assets/images/ecash.png",
                      "assets/images/down5.png",
                      "eCash",
                      "XEC",
                      "\$0.0001162",
                      "-13.41%%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/aave.png",
                      "assets/images/down3.png",
                      "Aave",
                      "AAVE",
                      "      \$242.13",
                      "-7.59%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/ada.png",
                      "assets/images/down2.png",
                      "Cardano",
                      "ADA",
                      "      \$1.149",
                      "-5.12%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/cosmos.png",
                      "assets/images/down1.png",
                      "Cosmos",
                      "ATOM",
                      "      \$30.02",
                      "-5.04%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/link.png",
                      "assets/images/down1.png",
                      "Chainlink",
                      "LINK",
                      "      \$17.41",
                      "-4.11%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/lite.png",
                      "assets/images/down5.png",
                      "Litecoin",
                      "LTC",
                      "      \$126.69",
                      "-3.28%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/ape.png",
                      "assets/images/down3.png",
                      "ApeCoin",
                      "APE",
                      "      \$13.01",
                      "-3.17%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/eth.png",
                      "assets/images/down1.png",
                      "Ethereum",
                      "ETH",
                      "\$3,490.20",
                      "-1.6%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/iota.png",
                      "assets/images/down1.png",
                      "IOTA",
                      "MIOTA",
                      "    \$0.8922",
                      "-0.87%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/enj.png",
                      "assets/images/down2.png",
                      "Enjin Coin",
                      "ENJ",
                      "    \$1.86",
                      "-0.82%",
                      0xFFFF0000,
                    ),
                  ],
                ),
              ),
            ),
            SingleChildScrollView(
              physics: BouncingScrollPhysics(),
              child: Padding(
                padding: const EdgeInsets.all(30.0),
                child: Column(
                  children: [
                    coin_get(
                      "assets/images/vinu.png",
                      "assets/images/usdt_graph.png",
                      "Vita Inu",
                      "VINU",
                      "0,00000421",
                      "+95.21%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/bnb.png",
                      "assets/images/bnb_graph.png",
                      "Binance",
                      "BNB",
                      "    \$428.2",
                      "+3.45%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/ada.png",
                      "assets/images/ada_graph.png",
                      "Cardano",
                      "ADA",
                      "      \$1.149",
                      "+5.12%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/doge.png",
                      "assets/images/doge_graph.png",
                      "DOGE",
                      "DOGE",
                      "      \$0.1387",
                      "+16.23%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/xrp.png",
                      "assets/images/xrp_graph.png",
                      "XRP",
                      "XRP",
                      "      \$0.089",
                      "+25.53%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/usdt.png",
                      "assets/images/usdt_graph.png",
                      "Tether",
                      "USDT",
                      "      \₺14.776",
                      "+0.11%",
                      0xFF006400,
                    ),
                    coin_get(
                      "assets/images/eth.png",
                      "assets/images/down1.png",
                      "Ethereum",
                      "ETH",
                      "\$3,490.20",
                      "-1.6%",
                      0xFFFF0000,
                    ),
                    coin_get(
                      "assets/images/ltc.png",
                      "assets/images/doge_graph.png",
                      "Uniswap",
                      "UNI",
                      "      \$11.21",
                      "+7.21%",
                      0xFF006400,
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      )),
    );
  }
}
